plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'pt.andreomlopes.wearsideloader'
    compileSdk 33

    defaultConfig {
        applicationId "pt.andreomlopes.wearsideloader"
        minSdk 24
        targetSdk 33
        versionCode 20
        versionName "0.2.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.5.1'
    implementation 'androidx.activity:activity-ktx:1.6.1'

    implementation 'com.github.MuntashirAkon:libadb-android:3.1.1'
    implementation 'com.github.MuntashirAkon:sun-security-android:1.1'
    implementation 'org.conscrypt:conscrypt-android:2.5.3'
}
